name: aprender_haciendo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_screenutil: ^0.4.2
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  google_sign_in: ^4.4.4
  http: ^0.12.1
  hidden_drawer_menu: ^1.1.4
  carousel_slider: ^2.2.1
  # flutter_launch: ^0.2.0
  flutter_svg: ^0.17.4
  google_fonts: ^1.1.0
  modal_progress_hud: ^0.1.3
  auto_size_text: ^2.0.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
    - icons/
    - fonts/
    - images/45025_Coding.png
    - images/wedo.png
    - images/steamP.png
    - images/lego_M.png
    - images/lego_M.jpg
    - images/breakdance_spike.png
    - images/legoAcademy.png
    - images/firstlego.png
    - images/WRO.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Muli
      fonts:
        - asset: fonts/muli-extrabold.ttf

