name: aprender_haciendo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_screenutil: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/LogoAH.png
    - assets/wedo2.png
    - assets/lego-spike.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf

